export const ansi = [
  [
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 2.1 },
  ],
  [
    { size: 1.6 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1.6 },
  ],
  [
    { size: 1.8 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 2.5 },
  ],
  [
    { size: 2.3 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 3 },
  ],
  [
    { size: 1.8 },
    { size: 1 },
    { size: 1 },
    { size: 1 },
    { size: 5.4 },
    { size: 1.5 },
    { size: 1 },
    { size: 1 },
    { size: 1.9 },
  ],
];
