export const colemak = [
  [
    { value: "`", staggered: "1em", linear: "1em" },
    { value: "1", staggered: "1em", linear: "1em" },
    { value: "2", staggered: "1em", linear: "1em" },
    { value: "3", staggered: "1em", linear: "1em" },
    { value: "4", staggered: "1em", linear: "1em" },
    { value: "5", staggered: "1em", linear: "1em" },
    { value: "6", staggered: "1em", linear: "1em" },
    { value: "7", staggered: "1em", linear: "1em" },
    { value: "8", staggered: "1em", linear: "1em" },
    { value: "9", staggered: "1em", linear: "1em" },
    { value: "0", staggered: "1em", linear: "1em" },
    { value: "-", staggered: "1em", linear: "1em" },
    { value: "=", staggered: "1em", linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "Backspace", staggered: "2em", linear: "1em", flexGrow: true },
  ],
  [
    { value: "Tab", staggered: "1.5em", linear: "1em" },
    { value: "Q", staggered: "1em", linear: "1em" },
    { value: "W", staggered: "1em", linear: "1em" },
    { value: "F", staggered: "1em", linear: "1em" },
    { value: "P", staggered: "1em", linear: "1em" },
    { value: "G", staggered: "1em", linear: "1em" },
    { value: "J", staggered: "1em", linear: "1em" },
    { value: "L", staggered: "1em", linear: "1em" },
    { value: "U", staggered: "1em", linear: "1em" },
    { value: "Y", staggered: "1em", linear: "1em" },
    { value: ";", staggered: "1em", linear: "1em" },
    { value: "[", staggered: "1em", linear: "1em" },
    { value: "]", staggered: "1em", linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "\\", staggered: "1.5em", linear: "1em", flexGrow: true },
  ],
  [
    { value: "Caps", staggered: "1.75em", linear: "1em" },
    { value: "A", staggered: "1em", linear: "1em" },
    { value: "R", staggered: "1em", linear: "1em" },
    { value: "S", staggered: "1em", linear: "1em" },
    { value: "T", staggered: "1em", linear: "1em" },
    { value: "D", staggered: "1em", linear: "1em" },
    { value: "H", staggered: "1em", linear: "1em" },
    { value: "N", staggered: "1em", linear: "1em" },
    { value: "E", staggered: "1em", linear: "1em" },
    { value: "I", staggered: "1em", linear: "1em" },
    { value: "O", staggered: "1em", linear: "1em" },
    { value: "'", staggered: "1em", linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "Enter", staggered: "2.25em", linear: "1em", flexGrow: true },
  ],
  [
    { value: "Shift", staggered: "2.25em", linear: "1em" },
    { value: "Z", staggered: "1em", linear: "1em" },
    { value: "X", staggered: "1em", linear: "1em" },
    { value: "C", staggered: "1em", linear: "1em" },
    { value: "V", staggered: "1em", linear: "1em" },
    { value: "B", staggered: "1em", linear: "1em" },
    { value: "K", staggered: "1em", linear: "1em" },
    { value: "M", staggered: "1em", linear: "1em" },
    { value: ",", staggered: "1em", linear: "1em" },
    { value: ".", staggered: "1em", linear: "1em" },
    { value: "/", staggered: "1em", linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "Shift", staggered: "2.75em", linear: "1em", flexGrow: true },
  ],
  [
    { value: "Ctrl", staggered: "1.25em", linear: "1em" },
    { value: "Win", staggered: "1.25em", linear: "1em" },
    { value: "Alt", staggered: "1.25em", linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "Space", staggered: "5em", flexGrow: true, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: " ", staggered: null, linear: "1em" },
    { value: "Alt", staggered: "1.25em", linear: "1em" },
    { value: "Win", staggered: "1em", linear: "1em" },
    { value: "Fn", staggered: "1em", linear: "1em" },
    { value: "Ctrl", staggered: "1.25em", linear: "1em" },
  ],
];
